import { db } from '@/db';
import { expenses } from '@/db/schema';

async function main() {
    const sampleExpenses = [
        // Travel expenses
        {
            userId: 4,
            amount: 1250.00,
            currency: 'USD',
            category: 'Travel',
            description: 'Round-trip flight to NYC for client meeting',
            expenseDate: new Date('2024-10-15').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-10-16').toISOString(),
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-18').toISOString(),
        },
        {
            userId: 7,
            amount: 380.50,
            currency: 'EUR',
            category: 'Travel',
            description: 'Hotel accommodation - Berlin conference',
            expenseDate: new Date('2024-11-20').toISOString(),
            paidBy: 'COMPANY_CARD',
            status: 'PENDING',
            submittedAt: new Date('2024-11-21').toISOString(),
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-21').toISOString(),
        },
        {
            userId: 5,
            amount: 85.00,
            currency: 'USD',
            category: 'Travel',
            description: 'Taxi to airport and return',
            expenseDate: new Date('2024-12-05').toISOString(),
            paidBy: 'PERSONAL',
            status: 'IN_PROGRESS',
            submittedAt: new Date('2024-12-06').toISOString(),
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-06').toISOString(),
        },
        {
            userId: 9,
            amount: 2150.00,
            currency: 'EUR',
            category: 'Travel',
            description: 'Business class flight to London - urgent client issue',
            expenseDate: new Date('2024-09-28').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-09-29').toISOString(),
            createdAt: new Date('2024-09-28').toISOString(),
            updatedAt: new Date('2024-10-02').toISOString(),
        },

        // Meals & Entertainment expenses
        {
            userId: 6,
            amount: 120.75,
            currency: 'USD',
            category: 'Meals & Entertainment',
            description: 'Team lunch after quarterly review meeting',
            expenseDate: new Date('2024-11-08').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-11-09').toISOString(),
            createdAt: new Date('2024-11-08').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 8,
            amount: 185.40,
            currency: 'EUR',
            category: 'Meals & Entertainment',
            description: 'Client dinner at upscale restaurant',
            expenseDate: new Date('2024-10-22').toISOString(),
            paidBy: 'COMPANY_CARD',
            status: 'PENDING',
            submittedAt: new Date('2024-10-23').toISOString(),
            createdAt: new Date('2024-10-22').toISOString(),
            updatedAt: new Date('2024-10-23').toISOString(),
        },
        {
            userId: 4,
            amount: 45.50,
            currency: 'USD',
            category: 'Meals & Entertainment',
            description: 'Coffee meeting with potential partner',
            expenseDate: new Date('2024-12-10').toISOString(),
            paidBy: 'PERSONAL',
            status: 'REJECTED',
            submittedAt: new Date('2024-12-11').toISOString(),
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-13').toISOString(),
        },
        {
            userId: 11,
            amount: 95.25,
            currency: 'EUR',
            category: 'Meals & Entertainment',
            description: 'Working lunch with development team',
            expenseDate: new Date('2024-09-15').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-09-16').toISOString(),
            createdAt: new Date('2024-09-15').toISOString(),
            updatedAt: new Date('2024-09-18').toISOString(),
        },

        // Office Supplies expenses
        {
            userId: 10,
            amount: 78.90,
            currency: 'EUR',
            category: 'Office Supplies',
            description: 'Notebooks, pens, and sticky notes for team',
            expenseDate: new Date('2024-11-12').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-11-13').toISOString(),
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 5,
            amount: 156.00,
            currency: 'USD',
            category: 'Office Supplies',
            description: 'Printer paper and ink cartridges',
            expenseDate: new Date('2024-10-03').toISOString(),
            paidBy: 'COMPANY_CARD',
            status: 'PENDING',
            submittedAt: new Date('2024-10-04').toISOString(),
            createdAt: new Date('2024-10-03').toISOString(),
            updatedAt: new Date('2024-10-04').toISOString(),
        },
        {
            userId: 12,
            amount: 89.75,
            currency: 'EUR',
            category: 'Office Supplies',
            description: 'Ergonomic mouse pad and desk organizer',
            expenseDate: new Date('2024-09-25').toISOString(),
            paidBy: 'PERSONAL',
            status: 'IN_PROGRESS',
            submittedAt: new Date('2024-09-26').toISOString(),
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-09-26').toISOString(),
        },

        // Software & Tools expenses
        {
            userId: 7,
            amount: 299.99,
            currency: 'EUR',
            category: 'Software & Tools',
            description: 'Annual Adobe Creative Suite license',
            expenseDate: new Date('2024-11-01').toISOString(),
            paidBy: 'COMPANY_CARD',
            status: 'APPROVED',
            submittedAt: new Date('2024-11-02').toISOString(),
            createdAt: new Date('2024-11-01').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },
        {
            userId: 4,
            amount: 149.00,
            currency: 'USD',
            category: 'Software & Tools',
            description: 'JetBrains IntelliJ IDEA license renewal',
            expenseDate: new Date('2024-10-18').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-10-19').toISOString(),
            createdAt: new Date('2024-10-18').toISOString(),
            updatedAt: new Date('2024-10-22').toISOString(),
        },
        {
            userId: 13,
            amount: 199.99,
            currency: 'EUR',
            category: 'Software & Tools',
            description: 'Sketch app license for UI design work',
            expenseDate: new Date('2024-09-10').toISOString(),
            paidBy: 'PERSONAL',
            status: 'REJECTED',
            submittedAt: new Date('2024-09-11').toISOString(),
            createdAt: new Date('2024-09-10').toISOString(),
            updatedAt: new Date('2024-09-14').toISOString(),
        },
        {
            userId: 6,
            amount: 75.00,
            currency: 'USD',
            category: 'Software & Tools',
            description: 'GitHub Copilot subscription - 6 months',
            expenseDate: new Date('2024-12-01').toISOString(),
            paidBy: 'PERSONAL',
            status: 'PENDING',
            submittedAt: new Date('2024-12-02').toISOString(),
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        },

        // Client Entertainment expenses
        {
            userId: 8,
            amount: 450.00,
            currency: 'EUR',
            category: 'Client Entertainment',
            description: 'Theater tickets for client and spouse',
            expenseDate: new Date('2024-11-25').toISOString(),
            paidBy: 'COMPANY_CARD',
            status: 'IN_PROGRESS',
            submittedAt: new Date('2024-11-26').toISOString(),
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-26').toISOString(),
        },
        {
            userId: 9,
            amount: 320.75,
            currency: 'EUR',
            category: 'Client Entertainment',
            description: 'Business dinner at Michelin star restaurant',
            expenseDate: new Date('2024-10-08').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-10-09').toISOString(),
            createdAt: new Date('2024-10-08').toISOString(),
            updatedAt: new Date('2024-10-12').toISOString(),
        },
        {
            userId: 5,
            amount: 280.00,
            currency: 'USD',
            category: 'Client Entertainment',
            description: 'Golf tournament entry fees for client meeting',
            expenseDate: new Date('2024-09-20').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-09-21').toISOString(),
            createdAt: new Date('2024-09-20').toISOString(),
            updatedAt: new Date('2024-09-24').toISOString(),
        },

        // Utilities expenses
        {
            userId: 10,
            amount: 125.50,
            currency: 'EUR',
            category: 'Utilities',
            description: 'Home office internet upgrade for remote work',
            expenseDate: new Date('2024-11-15').toISOString(),
            paidBy: 'PERSONAL',
            status: 'PENDING',
            submittedAt: new Date('2024-11-16').toISOString(),
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-16').toISOString(),
        },
        {
            userId: 4,
            amount: 89.99,
            currency: 'USD',
            category: 'Utilities',
            description: 'Business phone line monthly bill',
            expenseDate: new Date('2024-10-01').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-10-02').toISOString(),
            createdAt: new Date('2024-10-01').toISOString(),
            updatedAt: new Date('2024-10-05').toISOString(),
        },
        {
            userId: 12,
            amount: 65.00,
            currency: 'EUR',
            category: 'Utilities',
            description: 'Additional mobile data for client presentations',
            expenseDate: new Date('2024-09-12').toISOString(),
            paidBy: 'PERSONAL',
            status: 'REJECTED',
            submittedAt: new Date('2024-09-13').toISOString(),
            createdAt: new Date('2024-09-12').toISOString(),
            updatedAt: new Date('2024-09-16').toISOString(),
        },

        // Marketing expenses
        {
            userId: 6,
            amount: 850.00,
            currency: 'USD',
            category: 'Marketing',
            description: 'Google Ads campaign for Q4 product launch',
            expenseDate: new Date('2024-11-30').toISOString(),
            paidBy: 'COMPANY_CARD',
            status: 'APPROVED',
            submittedAt: new Date('2024-12-01').toISOString(),
            createdAt: new Date('2024-11-30').toISOString(),
            updatedAt: new Date('2024-12-04').toISOString(),
        },
        {
            userId: 11,
            amount: 425.75,
            currency: 'EUR',
            category: 'Marketing',
            description: 'Trade show booth materials and banners',
            expenseDate: new Date('2024-10-12').toISOString(),
            paidBy: 'PERSONAL',
            status: 'IN_PROGRESS',
            submittedAt: new Date('2024-10-13').toISOString(),
            createdAt: new Date('2024-10-12').toISOString(),
            updatedAt: new Date('2024-10-13').toISOString(),
        },
        {
            userId: 7,
            amount: 1200.00,
            currency: 'EUR',
            category: 'Marketing',
            description: 'LinkedIn advertising campaign setup',
            expenseDate: new Date('2024-09-08').toISOString(),
            paidBy: 'COMPANY_CARD',
            status: 'APPROVED',
            submittedAt: new Date('2024-09-09').toISOString(),
            createdAt: new Date('2024-09-08').toISOString(),
            updatedAt: new Date('2024-09-12').toISOString(),
        },
        {
            userId: 5,
            amount: 350.50,
            currency: 'USD',
            category: 'Marketing',
            description: 'Promotional brochures and business cards printing',
            expenseDate: new Date('2024-12-08').toISOString(),
            paidBy: 'PERSONAL',
            status: 'PENDING',
            submittedAt: new Date('2024-12-09').toISOString(),
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-09').toISOString(),
        },

        // Training & Development expenses
        {
            userId: 13,
            amount: 1850.00,
            currency: 'EUR',
            category: 'Training & Development',
            description: 'AWS Certified Solutions Architect bootcamp',
            expenseDate: new Date('2024-11-05').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-11-06').toISOString(),
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-11-10').toISOString(),
        },
        {
            userId: 8,
            amount: 599.00,
            currency: 'EUR',
            category: 'Training & Development',
            description: 'Tech conference ticket - DevOps Summit 2024',
            expenseDate: new Date('2024-10-25').toISOString(),
            paidBy: 'COMPANY_CARD',
            status: 'PENDING',
            submittedAt: new Date('2024-10-26').toISOString(),
            createdAt: new Date('2024-10-25').toISOString(),
            updatedAt: new Date('2024-10-26').toISOString(),
        },
        {
            userId: 4,
            amount: 299.99,
            currency: 'USD',
            category: 'Training & Development',
            description: 'Pluralsight annual subscription for team training',
            expenseDate: new Date('2024-09-30').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-10-01').toISOString(),
            createdAt: new Date('2024-09-30').toISOString(),
            updatedAt: new Date('2024-10-03').toISOString(),
        },
        {
            userId: 10,
            amount: 450.00,
            currency: 'EUR',
            category: 'Training & Development',
            description: 'Project Management certification course',
            expenseDate: new Date('2024-12-12').toISOString(),
            paidBy: 'PERSONAL',
            status: 'IN_PROGRESS',
            submittedAt: new Date('2024-12-13').toISOString(),
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-13').toISOString(),
        },
        {
            userId: 9,
            amount: 750.00,
            currency: 'EUR',
            category: 'Training & Development',
            description: 'Leadership workshop for senior developers',
            expenseDate: new Date('2024-09-18').toISOString(),
            paidBy: 'COMPANY_CARD',
            status: 'REJECTED',
            submittedAt: new Date('2024-09-19').toISOString(),
            createdAt: new Date('2024-09-18').toISOString(),
            updatedAt: new Date('2024-09-22').toISOString(),
        },

        // Additional mixed expenses
        {
            userId: 11,
            amount: 175.50,
            currency: 'EUR',
            category: 'Office Supplies',
            description: 'Whiteboard markers and cleaning supplies',
            expenseDate: new Date('2024-12-03').toISOString(),
            paidBy: 'PERSONAL',
            status: 'APPROVED',
            submittedAt: new Date('2024-12-04').toISOString(),
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-07').toISOString(),
        },
        {
            userId: 6,
            amount: 95.00,
            currency: 'USD',
            category: 'Utilities',
            description: 'Co-working space day pass for client meeting',
            expenseDate: new Date('2024-11-28').toISOString(),
            paidBy: 'PERSONAL',
            status: 'PENDING',
            submittedAt: new Date('2024-11-29').toISOString(),
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-29').toISOString(),
        },
        {
            userId: 12,
            amount: 220.00,
            currency: 'EUR',
            category: 'Software & Tools',
            description: 'Figma professional plan for design team',
            expenseDate: new Date('2024-10-30').toISOString(),
            paidBy: 'COMPANY_CARD',
            status: 'APPROVED',
            submittedAt: new Date('2024-10-31').toISOString(),
            createdAt: new Date('2024-10-30').toISOString(),
            updatedAt: new Date('2024-11-03').toISOString(),
        }
    ];

    await db.insert(expenses).values(sampleExpenses);
    
    console.log('✅ Expenses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});